---
title: "151AHW4"
author: "xuncheng Zhang"
date: "October 19, 2016"
output: html_document
---
#Q1

```{r}
n = 100

M = 1000
N = 2000
t.s = rep(NA,N)
diff = rep(NA,N)
count  = 0
for(i in 1:M){
    x = rnorm(n)
    t1 = sd(x)
  for(j in 1:N){
    x.s = sample(x,n,replace = T)
    t.s[j] = sd(x.s)
    diff[j] = t.s[j] - t1
  }
  low = mean(t.s) - quantile(diff,0.975)
  up = mean(t.s) - quantile(diff,0.025)
  if (low <= 1 & up >= 1)
    count = count + 1
}

q <- quantile(diff,c(.025,.975))
#The 95%CI 
c(t1 - q[2], t1 - q[1])
#Yes 1 is in the interval
#For how many 
count

```

#Q2
#a
```{r}
load("twoyear.RData")
ty = data
ty.desc = desc
ty.desc
head(ty)
M = lm(lwage ~ jc + univ + exper, data = ty)
summary(M)

m = lm(lwage ~ I(jc + univ) + exper, data = ty)
summary(m)
#T value for this test is 33.75, and since the p-value is super small, jc and univ does influence in the wage.And exper and intercept stay the same.
```
#b
```{r}
anova(m,M)

#The F value is 2.154, and p-value is bigger than 0.05 so we cannot reject the null hypothesis which suggests beta1 should be equal to beta2
```
#c
```{r}
K = 10000
fsts = numeric(K)
for(i in 1:K)
{
  plm = lm(lwage ~ I(jc + univ) + sample(univ) + exper, data = ty)
  fsts[i] = summary(plm)$fstat[1]
}
pval = length(fsts[fsts>summary(M)$fstat[1]])/K
pval 

#Since the p-value is larger than 0.05, we cannot reject the null which suggests beta1 = beta2
```
#d
```{r}
N = 2000
b.s = matrix(NA, N, 4)
for(i in 1:N){
  new.y = M$fitted.values + sample(M$residuals,replace = T)
  m.s = lm(new.y~ I(jc + univ)+sample(univ) + exper, data = ty )
  b.s[i,] = m.s$coefficients
}

quantile(b.s[,3],c(0.05,0.95))
#Yes it contains 0
```

#Q3
#a
```{r}
library("faraway")
mod = lm(sr~pop15+pop75+dpi+ddpi,data = savings)
summary(mod)
confint(mod)
```
#b
```{r}
N = 2000
b.s = matrix(NA, N, 5)
for(i in 1:N){
  new.y = mod$fitted.values + sample(mod$residuals,replace = T)
  m.s = lm(new.y~pop15+pop75+dpi+ddpi,data = savings )
  b.s[i,] = m.s$coefficients
}

quantile(b.s[,2],c(0.025,0.975))
quantile(b.s[,3],c(0.025,0.975))
quantile(b.s[,4],c(0.025,0.975))
quantile(b.s[,5],c(0.025,0.975))

```

#Q4
```{r}
body = read.delim("bodyfat_corrected.txt", header = TRUE, sep = "")
M = lm(BODYFAT ~ AGE + WEIGHT + HEIGHT + THIGH, data = body)
#a
plot(M$fitted.values, M$residuals,xlab = "Fitted Values", ylab = "Residuals")
order(M$fitted.values, decreasing = T)[1:3]

#b
plot(M$fitted.values, rstandard(M), xlab = "Fitted Values", ylab = "Standardized Residuals")
order(M$fitted.values, decreasing = T)[1:3]

#c
plot(M$residuals,rstandard(M),xlab = "Residuals", ylab = "Standardized Residuals")
order(M$residuals,decreasing = F)[1:2]

#d
P_residuals = M$residuals/(1-influence(M)$hat)
plot(P_residuals,M$fitted.values, xlab = "Predicted residuals", ylab = "fitted values")
which(M$fitted.values > 40)

#e
plot(M$residuals,P_residuals, xlab = "Residuals", ylab = "predicted residuals")
order(M$residuals,decreasing = F)[1:2]
#f
plot(M$residuals,influence(M)$hat, xlab = "Residuals", ylab= "leverage")
which(influence(M)$hat > 0.1)

#g
plot(P_residuals,rstudent(M), xlab = "Predicted residuals", ylab = "Standardized Predicted Residuals")
which(rstudent(M) <(-3))

#h
plot(rstandard(M),rstudent(M), xlab = "Standardized residuals", ylab = "Standardized Predicted residuals")
which(rstudent(M) < (-3))

#i
plot(cooks.distance(M),1:nrow(body), xlab = "Cooks Distance", ylab = "ID")
order(cooks.distance(M),decreasing = T)[1:2]

```
#b
```{r}
p_value = sapply(rstudent(M), function(x){1 - pt(x,252)})
plot(1:nrow(body),p_value , xlab = "ID", ylab = "P-value")
abline(h=0.05)

sum(p_value < 0.05)
```
#c
```{r}
Modify <- lm(BODYFAT ~ AGE + WEIGHT + HEIGHT + THIGH, data = body[-c(39,42),])
summary((Modify))
```

